# Generated by Django 4.2.3 on 2023-07-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name'], 'verbose_name': 'Menu item'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['purchase_time'], 'verbose_name': 'Purchase'},
        ),
        migrations.AlterModelOptions(
            name='reciperequirement',
            options={'ordering': ['menu_item'], 'verbose_name': 'Recipe requirement'},
        ),
    ]
