# Generated by Django 4.2.3 on 2023-07-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='recipe_requirement',
            new_name='recipe_requirements',
        ),
    ]
