# Generated by Django 4.2.3 on 2023-08-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_recipe_requirement_menuitem_recipe_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='recipe_requirements',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient_quantity_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
