# Generated by Django 4.2.3 on 2023-08-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_menuitem_recipe_requirements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='ingredient_quantity_required',
            new_name='ingredient_quantity',
        ),
    ]
