# Generated by Django 4.2.3 on 2023-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('GR', 'g (Grams)'), ('KG', 'Kg (Kilograms)'), ('ML', 'ml (Mililitres)'), ('LI', 'L (Litres)'), ('NU', ''), ('TS', 'Tsp (Teaspoon)'), ('TB', 'Tbsp (Tablespoon)')], help_text='Please choose a unit of measurement from the available options.', max_length=2),
        ),
    ]
