# Generated by Django 4.2.3 on 2023-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('GR', 'g (grams)'), ('KG', 'kg (kilograms)'), ('ML', 'ml (mililitres)'), ('LI', 'l (litres)'), ('NU', ''), ('TS', 'tsp (teaspoon)'), ('TB', 'tbsp (tablespoon)')], help_text='Please choose a unit of measurement from the available options.', max_length=2),
        ),
    ]
