# Generated by Django 4.2.3 on 2023-08-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_reciperequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('GR', 'g'), ('KG', 'kg'), ('ML', 'ml'), ('LI', 'l'), ('NU', '')], help_text='Please choose a unit of measurement from the available options.', max_length=2),
        ),
    ]
