# Generated by Django 4.2.3 on 2023-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('GR', 'g'), ('KG', 'kg'), ('ML', 'ml'), ('LI', 'l'), ('NU', 'count')], help_text='Please choose a unit of measurement from the available options.', max_length=2),
        ),
    ]
