# Generated by Django 4.2.3 on 2023-08-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_ingredient_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('GR', 'g'), ('KG', 'kg'), ('ML', 'ml'), ('LI', 'l'), ('NU', 'count')], help_text='Choose the measurement unit that will be used in recipes', max_length=2),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='menuitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.menuitem'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ingredient'),
        ),
    ]
