# Generated by Django 4.2.3 on 2023-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recipe_instructions',
            field=models.TextField(blank=True, help_text='Instrctions for preparing this menu item'),
        ),
    ]
