# Generated by Django 4.2.3 on 2023-08-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_menuitem_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='recipe_instructions',
            field=models.TextField(blank=True, help_text='Instructions for preparing this menu item'),
        ),
    ]
