# Generated by Django 4.2.3 on 2023-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_menuitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
