# Generated by Django 4.2.3 on 2023-09-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_ingredient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciperequirement',
            options={'ordering': ['ingredient'], 'verbose_name': 'Recipe requirement'},
        ),
    ]
