# Generated by Django 4.2.3 on 2023-10-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_reciperequirement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('GR', 'grams'), ('KG', 'kilograms'), ('ML', 'mililitres'), ('LI', 'litres'), ('OU', 'ounces'), ('LB', 'lbs'), ('TS', 'tsp'), ('TB', 'tbsp'), ('CU', 'cups'), ('NU', 'count')], help_text='Choose the measurement unit that will be used in recipes', max_length=2),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='recipe_instructions',
            field=models.TextField(blank=True),
        ),
    ]
