# Generated by Django 4.2.3 on 2023-10-31 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
